.github/workflows/deploy-dev-pr.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-storybook-pr.yml
.github/workflows/deploy-storybook.yml

커밋 이후 Deploy되는 정적 페이지의 링크를 제공합니다.
커밋 메시지 우측의 결과 아이콘 -> Details를 통해 확인할 수 있습니다.

[BNG-33] Provide Preview URLs for every Deployment

---

.github/workflows/lint.yml
.husky/pre-commit
package-lock.json
package.json

`husky`와 `lint-staged` 활용하여 커밋 전 lint 검사 수행을 정의하였습니다.
closes #7

[BNG-35] ✅ Apply pre commit and post push & PR

---

package.json
src/styles/global.css

Figma에서 정의한 색, 폰트, 그림자 설정값 정의
* `@import` 사용하여 `src/styles/global.css`에서 해당 변수 로드
* 폰트 변수는 `font: var(--font-title-pc)`와 같이 사용
* 그림자 변수는 `box-shadow: var(--shadow)`로 사용

💄 Define global style variables

---

.eslintrc.json
src/App.jsx
src/components/State/State.jsx
src/stories/Button.jsx
src/stories/Header.jsx
src/stories/Page.jsx

- [v] `react/react-in-jsx-scope` 끄기
- [v] `prettier/prettier`의 수준 `warn`으로 변경
- Resolved: #36

🚨 Moderate lint not to error react import and prettier

---

src/components/Notice/Notice.jsx
src/components/Notice/Notice.stories.jsx
src/components/Notice/index.js
src/components/Notice/notice.module.css

- 닫기 눌렀을 때 버튼이 사라져야하는거 맞죠?
- 
- 
-

[BNG-60] UI/notice component

---

src/components/BreadCrumbs/BreadCrumbs.jsx
src/components/BreadCrumbs/BreadCrumbs.stories.js
src/components/BreadCrumbs/bread-crumbs.module.css
src/components/BreadCrumbs/icons/Chevron.jsx
src/components/BreadCrumbs/index.js

- items로 props를 받고 있는데, 이게 맞을까요?
- Resolved: #52

[BNG-74] BreadCrumbs 컴포넌트 개발

---

src/styles/table.css

[BNG-88] change table css

---

src/components/Button/Button.jsx
src/components/Button/Button.stories.js
src/components/Button/button.module.css
src/styles/global.css

- Button Component의 round css 코드
- Resolved: #72

[BNG-89] Button Component 추가

---

.github/workflows/deploy-dev-pr.yml
package.json
src/App.jsx

[BNG-86] React Webapp Dev PR Server Deploy 문제 해결

---

src/components/Input/Input.jsx
src/styles/global.css

[BNG-91] fix bug in css, input use effect

---

src/components/DatePicker/CustomDatePicker.jsx
src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/datepicker.module.css

- date==null 핸들링 시 아래와 같이 처리하는게 일반적인가요?
`   {hasError && (
<div className={styles.errorMessage}>날짜를 선택해주세요</div>
)}`
- inputClass가 길어져서 const로 따로 뺐는데 이렇게 처리해도 되나요?
- Resolved: #81

[BNG-94] Datepicker exception 상태 추가

---

src/components/Input/Input.jsx

- 외부에서 mode입력에 대한 UI 반영이 되지 않아 mode에 대한 useEffect를 추가했습니다.
- 
- 
-

[BNG-98] Input 컴포넌트 추가 보완 

---

.eslintrc.json
.vscode/settings.json
jsconfig.json
package.json
src/App.jsx
src/components/BreadCrumbs/bread-crumbs.module.css
src/components/Stepper/Stepper.jsx
src/components/Switch/Switch.jsx
src/contexts/AdjustContext.jsx
src/layouts/AdjustEditLayout/AdjustEditLayout.jsx
src/layouts/AdjustEditLayout/adjust-edit-layout.module.css
src/layouts/AdjustEditLayout/index.js
src/layouts/AppLayout/AppLayout.jsx
src/layouts/AppLayout/app-layout.module.css
src/layouts/AppLayout/index.js
src/pages/TestEditPage/TestEditPage.jsx
src/pages/TestEditPage/index.js
src/pages/TestPage/TestPage.jsx
src/pages/TestPage/index.js
src/styles/global.css

[BNG-99] 3.21 회의 사항 반영

---

src/components/Switch/Switch.jsx
src/components/Switch/Switch.stories.jsx

♻️ delegate state management to parent component

---

src/components/Button/Button.jsx

- 따로 수정할 부분은 없어서 className size 부분만 수정했어요
- 
- 
-

[BNG-103] Button component

---

src/components/Input/Input.jsx
src/components/Input/Input.stories.jsx

[BNG-106] Input component 수정

---

src/components/Slider/CustomSlider.jsx
src/components/Slider/Slider.stories.jsx

[BNG-105] Slider Component 수정

---

.github/workflows/deploy-dev-pr.yml

* develop 브랜치에서 배포되는 웹앱에 접근이 가능하도록 수정
* 배포 Annotation 수정
- Resolved: #111

[BNG-112] 💚 Correct dev pr deployment preview url

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/Dropdown.stories.jsx
src/components/Dropdown/dropdown.module.css

[BNG-114] Dropdown Custom

---

src/App.jsx
src/index.jsx

- createBrowserRouter
- Resolved: #119

[BNG-116] createBrowserRouter 적용

---

src/components/CheckBox/CheckBox.jsx
src/components/CheckBox/CheckBox.stories.jsx

[BNG-115] Checkbox Component Default값 설정

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/Dropdown.stories.jsx
src/components/Dropdown/dropdown.module.css

Dropdown customWidth : number -> string으로 변경

---

src/layouts/AdjustEditLayout/AdjustEditLayout.jsx

[BNG-118] blocker 오류 수정

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/dropdown.module.css

table-cell 안에 dropdown이 들어갔을 때 "dropdown-area" style로 인해 크기 조정이 불가능한것을 확인하였습니다.
그래서 fit-content로 되어있는것을 100%로 수정하였습니다.
- 
- 
- 
-

[BNG-119] Dropdown 컴포넌트 스타일 수정

---

src/hooks/use-blocker.module.css

[BNG-120] blocker font 적용

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/dropdown.module.css

Dropdown background color 추가 

---

src/components/TableOption/TableOption.jsx
src/components/TableOption/TableOption.stories.jsx

[BNG-125] 추가 prevfilter, prevsortlist

---

src/components/Modal/Modal.jsx
src/components/Modal/Register/RegisterModal.jsx
src/components/TableOption/Filter/FilterModal.jsx
src/components/TableOption/Sort/SortModal.jsx
src/components/TableOption/TableOption.jsx

- 위치 설정을 하도록 추가한 Props가 적절한지 확인 부탁드립니다
- Resolved: #152

[BNG-128] Modal 컴포넌트 CSS 수정

---

src/components/Pagination/PageInput/PageInput.jsx
src/components/Pagination/PageInput/page-input.module.css
src/components/Pagination/PageSelect/PageSelect.jsx
src/components/Pagination/Pagination.jsx
src/components/Pagination/Pagination.stories.js

[BNG-129] Pagination 수정

---

src/components/Pagination/PageInput/PageInput.jsx
src/components/Pagination/Pagination.jsx

[BNG-130] Pagination final 수정

---

src/components/Modal/modal.module.css

[BNG-132] modal.module.css에서 .filters 스타일 top, left 속성 제거

---

src/components/Modal/modal.module.css

[BNG-133] Modal css z-index 추가

---

src/components/TableOption/TableOption.jsx

🐛 Show selected filter, sort keys in TableOption

---

src/components/TimeLine/CustonTimeLine.jsx
src/components/TimeLine/TimeLine.stories.jsx

- min max 연도 입력하면 제대로 나오는지
- Resolved: #159

[BNG-131] timeline 버그 수정

---

src/components/TableSelectIndicator/TableSelectIndicator.jsx
src/components/TableSelectIndicator/TableSelectIndicator.stories.jsx
src/components/TableSelectIndicator/index.js
src/components/TableSelectIndicator/table-select-indicator.module.css

[BNG-135] TableSelectIndicator Component 개발

---

src/components/TableOption/Sort/SortModal.jsx
src/components/TableOption/TableOption.jsx

[BNG-138] SortModal : value -> order로 변경

---

src/pages/OrganizationSubject/OrganizationSubject.jsx

대상자편성페이지 targetValue 수정

---

src/App.jsx
src/pages/ResultPage/Card.jsx
src/pages/ResultPage/ResultPage.jsx

[BNG-139] fix bug in card mode, change card number

---

src/components/Stepper/Step.jsx
src/components/Stepper/Stepper.jsx
src/components/Stepper/mockStepperApiResponse.js
src/components/Stepper/step.module.css
src/contexts/AdjustContext.jsx
src/layouts/AdjustEditLayout/AdjustEditLayout.jsx
src/pages/AdjSubjectCriteria/AdjSubjectCriteriaPage.jsx
src/pages/Compensation/CompensationPage.jsx
src/pages/HighOrganization/HighOrganizationPage.jsx
src/pages/OrganizationSubject/OrganizationSubject.jsx
src/pages/PaybandApply/PaybandApplyPage.jsx
src/pages/PaybandConfig/PaybandConfigPage.jsx
src/pages/ResultPage/ResultPage.jsx

✨ Maintain current working step id context

---

src/pages/OrganizationSubject/OrganizationSubject.jsx

[BNG-140] 대상자 편성 가데이터 만들기

---

src/components/Stepper/Stepper.jsx
src/pages/HighOrganization/HighOrganizationPage.jsx

[BNG-144] stepper 에러 고치기

---

src/pages/HighOrganization/HighOrganizationPage.jsx

Fix typo high organization page

---

src/components/Notice/notice.module.css
src/contexts/ErrorHandlerContext.jsx
src/layouts/AdjustEditLayout/AdjustEditLayout.jsx
src/layouts/RootLayout/RootLayout.jsx
src/pages/TestPage/TestPage.jsx
src/utils/error.js

- Error Handler context 개발 
- Resolved: #198

✨ Create error handler

---

src/pages/MainPage/AdjustTableRow.jsx

✏️ 연봉 조정 조회 페이지 컬럼 수정

---

src/contexts/AdjustContext.jsx
src/layouts/AdjustEditLayout/AdjustEditLayout.jsx
src/pages/TestPage/TestPage.jsx

- 백엔드로부터 받은 조정 기본정보 (id, title) 컨텍스트로 전달

♻️ Pass adjust obj {id, title} from adjustContext

---

src/components/Stepper/Step.jsx
src/components/Stepper/Stepper.jsx
src/components/Stepper/Stepper.stories.js
src/components/Stepper/step.module.css
src/contexts/AdjustContext.jsx
src/layouts/AdjustEditLayout/AdjustEditLayout.jsx

✨ Enable step api call

---

src/components/Modal/Register/RegisterModal.jsx
src/components/Modal/modal.module.css

[BNG-194] RegisterModal 수정

---

src/components/Pagination/Pagination.jsx
src/components/Pagination/Pagination.stories.js

[BNG-189] pagination param 추가

---

src/components/Pagination/PageInput/PageInput.jsx

[BNG-191] PageInput 수정

---

src/pages/adjust-edit/criteria/PaybandCriteriaPage/PaybandCriteriaPage.jsx

[BNG-185] payband 설정 api 연결

---

src/pages/TestPage/TestPage.jsx
src/pages/adjust-edit/criteria/SubjectCriteriaPage/GradeSelection/GradeSelection.jsx
src/pages/adjust-edit/criteria/SubjectCriteriaPage/SubjectCriteriaPage.jsx

- 불필요한 코드가 존재하는지, useSWR의 쓰임새가 적절한지 확인해주세요 :)
- Resolved: #204

[BNG-175] 대상자 기준 설정 페이지 API 연결

---

src/pages/TestPage/TestPage.jsx
src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyPage.jsx

[BNG-173] Payband 적용 페이지 API 연결

---

src/pages/MainPage/AdjustTable.jsx
src/pages/MainPage/MainPage.jsx

[BNG-211] 연봉 조정 페이지 수정

---

src/components/SnackBar/SnackBar.jsx
src/components/SnackBar/SnackBar.stories.jsx
src/components/SnackBar/index.js
src/components/SnackBar/snackbar.module.css
src/layouts/AdjustEditLayout/AdjustEditLayout.jsx
src/pages/adjust-edit/main/ResultPage/ResultPage.jsx

- snack bar 디자인
- Resolved: #253

[BNG-221] 통합 인사 반영 여부, snack bar

---

src/pages/MainDashboardPage/EmploymentTypeDistributionChart.jsx
src/pages/MainDashboardPage/GradeDistributionChart.jsx
src/pages/MainDashboardPage/MainDashboardPage.jsx
src/pages/MainDashboardPage/SalaryGradeTrendChart.jsx
src/pages/MainDashboardPage/TenureDistributionChart.jsx
src/pages/MainDashboardPage/main-chart-page.module.css
src/pages/MainDashboardPage/main-dashboard-page.module.css

[BNG-224] Main 차트 대시보드 스타일 수정

---

src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyArea.jsx
src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyTable.jsx

[BNG-225] Payband 적용 페이지네이션 수정

---

src/layouts/AdjustEditLayout/AdjustEditLayout.jsx
src/pages/adjust-edit/criteria/PaybandCriteriaPage/PaybandCriteriaPage.jsx
src/pages/adjust-edit/criteria/PaymentRateCriteriaPage/PaymentRateCriteriaPage.jsx
src/pages/adjust-edit/criteria/SubjectCriteriaPage/SubjectCriteriaPage.jsx
src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyPage.jsx
src/pages/adjust-edit/main/ResultPage/ResultPage.jsx
src/pages/adjust-edit/preparation/HpoApplyPage/HpoApplyPage.jsx
src/pages/adjust-edit/preparation/SubjectAssignPage/SubjectAssignPage.jsx

[BNG-229] 스낵바, 결과페이지 에러

---

src/pages/adjust-edit/preparation/HpoApplyPage/HpoApplyPage.jsx
src/pages/adjust-edit/preparation/HpoApplyPage/HpoApplyTable.jsx

고성과조직 가산 대상 여부 페이지 총 페이지 추가

---

src/layouts/AppLayout/AppLayout.jsx
src/layouts/AppLayout/AppLayout.module.css
src/layouts/RootLayout/RootLayout.jsx

[BNG-230] 데이터이쿠 링크 달기

---

src/pages/MainPage/FilterSort.jsx
src/pages/MainPage/NoDataTable.jsx

[BNG-232] 연봉 조정 등록 버튼 css 수정

---

src/pages/adjust-edit/preparation/SubjectAssignPage/SubjectAssignPage.jsx

[BNG-233] 대상자 편성 페이지 totalPage수정

---

src/components/TimeLine/CustonTimeLine.jsx
src/pages/MainDashboardPage/EmploymentTypeDistributionChart.jsx
src/pages/MainPage/MainPage.jsx
src/pages/MainPage/NoDataTable.jsx
src/pages/adjust-edit/criteria/PaymentRateCriteriaPage/PaymentRateCriteriaPage.jsx

[BNG-234] 메인페이지 오류

---

src/pages/adjust-edit/preparation/SubjectAssignPage/SubjectAssignPage.jsx

[BNG-233] 대상자 편성 엑셀다운 수정

---

src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyTable.jsx
src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyTableRow.jsx

[Payband 적용 페이지] 상한 하한

---

src/pages/MainPage/MainPage.jsx

[BNG-236] MAIN페이지 버그 수정

---

src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyArea.jsx
src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyPage.jsx

Payband 적용 페이지 엑셀 다운로드

---

src/components/TimeLine/CustonTimeLine.jsx

[BNG-241] timeline 높이 오류

---

src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyTableRow.jsx

[Payband 적용 페이지] 기준연봉 천단위 아래 버림

---

src/pages/adjust-edit/preparation/HpoApplyPage/HpoApplyPage.jsx

[BNG-244] 필터 검색 기능 추가

---

src/layouts/AdjustEditLayout/AdjustEditLayout.jsx
src/pages/adjust-edit/criteria/PaybandCriteriaPage/PaybandCriteriaPage.jsx
src/pages/adjust-edit/criteria/PaymentRateCriteriaPage/PaymentRateCriteriaPage.jsx
src/pages/adjust-edit/criteria/SubjectCriteriaPage/SubjectCriteriaPage.jsx

[BNG-243] 스낵바 오류

---

src/pages/adjust-edit/criteria/PaymentRateCriteriaPage/PaymentRateCriteriaPage.jsx

[보상지급률 페이지] Input값 Null일 경우 저장 막기

---

src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyPage.jsx

[Payband 적용 페이지] null 값 처리

---

src/layouts/AdjustEditLayout/AdjustEditLayout.jsx

[BNG-247] 결과 페이지 mutate 추가

---

src/pages/AdjustHistoryPage/AdjustHistoryPage.jsx

[BNG-249] 모바일 에러

---

src/pages/adjust-edit/main/PaybandApplyPage/PaybandApplyPage.jsx

Payband 적용 페이지 소제목 수정 

---

src/pages/adjust-edit/preparation/HpoApplyPage/FilterSort.jsx

Reverts bongsco/posco-salary-react-app#310

Release v1.0.2 (Revert Release v1.0.3)
